### ISSUE TITLE
data-tooltip change doesn't show tooltip text

### ISSUE THREAD

**Issue by robertmausser** [cgkineo/adapt-pageNav#25]
Changing to data-tooltip now doesn't seem to make the tooltips show as popup text for each button. It just shows an arrow. Is this intentional? Is having the tooltip popups as text not compatible with proper validation?

**Comment by oliverfoster** [comment]
apologies, [i missed a line](https://github.com/cgkineo/adapt-pageNav/commit/6aa1d4178add99f1218169d24d884dcc27e54e9b), try v2.0.5
