### ISSUE TITLE
Close function should call LMS close function

### ISSUE THREAD

**Issue by simondate** [cgkineo/adapt-pageNav#26]
The Close [extension attempts to call the function](https://github.com/cgkineo/adapt-close/blob/master/js/adapt-close.js#L51-L61) `scormWrapperInstance.finish();` before calling `top.window.close();`

This extension just calls `top.window.close();`, without anything else. Why don't we copy that code snippet to this extension?

**Comment by oliverfoster** [comment]
Is there a reason for this pr?

**Comment by simondate** [comment]
If a learner is in an LMS that uses frameset for SCORM content then `top.window.close()` alone won't exit the course. The other Adapt plugin that uses this function, adapt-close, [uses this additional fallback](https://github.com/cgkineo/adapt-close/blob/master/js/adapt-close.js#L51-L61).

**Comment by oliverfoster** [comment]
try https://github.com/cgkineo/adapt-pageNav/pull/29
