### ISSUE TITLE
Update and modernize code

### ISSUE THREAD

**Issue by swashbuck** [cgkineo/adapt-pageNav#41]
### Subject of the issue
The Page Nav plugin codebase needs to be updated / modernized. This would include:
* ES6 syntax
* JSX template
* Update documentation as needed

In addition, it has been mentioned that there is too many config options and that the plugin config could be streamlined. Look into decluttering the interface / setup.

**Comment by oliverfoster** [comment]
3. probably not
4. b. it's difficult to map the number of siblings to the number of text labels unless the override for page nav lives on the sibling with its alternative title

**Comment by swashbuck** [comment]
I'm at a stopping point with PR #49 until we resolve the questions above.

**Comment by oliverfoster** [comment]
1. Icon alignment (left/right/top/bottom/auto)
2. Yes to default
4. Remove siblings from pageNav
5. Remove _returnToPreviousLocation
6. Keep lock until page complete
7. Keep looping
8. Leave in _classes
9. Yes, make it consistent with adapt-close

**Comment by swashbuck** [comment]
> 9. Yes, make it consistent with adapt-close

I've moved this one to #50
