### ISSUE TITLE
Optimise RTL styling

### ISSUE THREAD

**Issue by guywillis** [cgkineo/adapt-pageNav#52]
### Subject of the enhancement
The RTL styling present in the `pageNav.less` file could be optimised a touch better by utilising the [padding-inline-start](https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-start) and [padding-inline-end](https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline-end) properties instead of the current approach.

The `padding-inline-start` and `padding-inline-end` properties do not require an associated RTL version as the property inherits the body direction.

### Your environment
* Master

**Comment by oliverfoster** [comment]
Not ie compatible.
