### ISSUE TITLE
Reimplement _returnToPreviousLocation selector

### ISSUE THREAD

**Issue by guywillis** [cgkineo/adapt-pageNav#55]
### Subject of the issue
We currently use the `_returnToPreviousLocation` option in projects to return users to their previous position in the course if they navigate away to another page e.g. a help page. 

We do supplement this button with the navigation back button but find it provides a better user flow to the page to have a button at the end that returns them to their previous location.

Tagging @swashbuck @oliverfoster for visibility

### Your environment
* Master FW & AAT

**Comment by swashbuck** [comment]
@guywillis Sorry about that. I should be able to restore some of this work from the `issue/41` branch from before the team decided to axe the option.

**Comment by swashbuck** [comment]
@guywillis PR #56 is ready for review.
